CREATE TABLE IF NOT EXISTS `ferramenta_consulta_extrato_creditos_usuario` (
  `id_extrato` int(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` int(11) NOT NULL,
  `hash_movimentacao` char(64) NOT NULL,
  `idtransacao` varchar(120) DEFAULT NULL,
  `tipo` char(1) NOT NULL,
  `valor` decimal(10,2) NOT NULL DEFAULT 0.00,
  `descricao` varchar(500) NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT 1,
  `status` varchar(40) NOT NULL DEFAULT 'ativo',
  `data_movimentacao` datetime NOT NULL,
  `origem` varchar(40) NOT NULL DEFAULT 'api_creditos',
  `id_consulta_usuario` int(11) DEFAULT NULL,
  `id_consulta` int(11) DEFAULT NULL,
  `raw_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_extrato`),
  UNIQUE KEY `uniq_extrato_hash_movimentacao` (`hash_movimentacao`),
  KEY `idx_extrato_usuario_data` (`id_usuario`, `data_movimentacao`),
  KEY `idx_extrato_idtransacao` (`idtransacao`),
  KEY `idx_extrato_consulta_usuario` (`id_consulta_usuario`),
  KEY `idx_extrato_consulta` (`id_consulta`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
